package com.chilik1020.framework.utils

const val BASE_URL: String = "http://188.120.232.83:8080/"
const val BASE_URL_POST_IMAGE: String = "http://188.120.232.83:8080/mustachepaws/posts/image/"

const val PREFERENCE_FILE_NAME = "APP_PREFERENCES"
const val PREFERENCE_TOKEN_KEY = "ACCESS_TOKEN"
const val PREFERENCE_USER_ID_KEY = "USER_ID"
const val PREFERENCE_USER_NAME_KEY = "USER_NAME"
const val PREFERENCE_USER_FIRSTNAME_KEY = "USER_FIRSTNAME"
const val PREFERENCE_USER_LASTNAME_KEY = "USER_LASTNAME"
const val PREFERENCE_USER_EMAIL_KEY = "USER_EMAIL"
const val PREFERENCE_USER_PHONENUMBER_KEY = "USER_PHONENUMBER"
const val PREFERENCE_USER_CREATED_AT_KEY = "USER_CREATED_AT"

const val LOG_TAG = "___MUSTACHE_PAWS___"